version: 2.1

aliases:
  - &ci-build-image quay.io/yeebase/ci-build:7.2
  - &workspace_root ~/workspace

  - &save_composer_cache
    key: composer-cache-v1-{{ .Branch }}-{{ checksum "composer.json" }}
    paths:
      - /composer/cache-dir

  - &restore_composer_cache
    keys:
      - composer-cache-v1-{{ .Branch }}-{{ checksum "composer.json.ci" }}
      - composer-cache-v1-{{ .Branch }}-
      - composer-cache-v1-

  - &attach_workspace
     at: *workspace_root

  - &persist_to_workspace
    root: .
    paths: 
      - .

jobs:
  checkout:
    docker:
      - image: *ci-build-image
    environment:
      COMPOSER_CACHE_DIR: /composer/cache-dir
    steps:
      - checkout
      - restore_cache: *restore_composer_cache
      
      - run: |
          mkdir graphql
          shopt -s extglob dotglob
          mv !(graphql) graphql
          shopt -u dotglob
          cp graphql/composer.json.ci composer.json
          cp graphql/phpcs.xml.dist phpcs.xml.dist
          composer update

      - save_cache: *save_composer_cache
      - persist_to_workspace: *persist_to_workspace

  lint:
    working_directory: *workspace_root
    docker:
      - image: *ci-build-image
    steps:
      - attach_workspace: *attach_workspace
      - run: bin/phpcs graphql/Classes

  tests:
    working_directory: *workspace_root
    docker:
      - image: *ci-build-image
    environment:
      FLOW_CONTEXT: Testing
    steps:
      - attach_workspace: *attach_workspace
      - run:
          bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml graphql/Tests/Functional

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - tests:
          requires:
            - checkout